version: "3.8"

services:
  app:
    image: ${DOCKER_USERNAME}/gongdori-server:latest
    container_name: gongdori-server-container
    restart: unless-stopped

    ports:
      - "${APP_PORT}:8080"

    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: ${JAVA_OPTS}

      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      AES_KEY: ${AES_KEY}
      JWT_KEY: ${JWT_KEY}
      JWT_ACCESS: ${JWT_ACCESS}
      JWT_REFRESH: ${JWT_REFRESH}

    networks:
      - gongdori-network

networks:
  gongdori-network:
    external: true